Suggested changes to README
Hackathonners/vania pull request #3
Opened 2017-03-28 15:36 UTC by MarcoCouto

2017-03-28 20:29 UTC, fntneves requested changes
See my comments.

Also, remove the following line from **Usage** section, or change it to describe the use case scenario.
*A quick example for 3 abstract targets, 4 abstract objects and the following weight matrix.*

2017-03-28 20:29 UTC, fntneves commented on README.md
> +* **weight**: a map from **object** to **target**, which represents the cost of assigning the first to the second.
*weights*. Is it really a map? It is actually a list of lists.
I think we could call it 'matrix'.

2017-03-28 20:29 UTC, fntneves commented on README.md
> +Using linear programming, the **weights** of the **targets** relative to the **objects** are taken into consideration and used to build the constraints of an Integer Linear Programming (ILP) model. A
*in order to distribute*

2017-03-28 20:29 UTC, fntneves commented on README.md
> +Three lists are given as input to the module: **objects**, **targets** and **weights**.
The following three lists ...

2017-03-28 20:29 UTC, fntneves commented on README.md
> + * The difference between the weight distributed by **targets** is minimal.
between the individual weight of each target is minimal.

2017-03-29 09:26 UTC, MarcoCouto commented on README.md
> +* **weight**: a map from **object** to **target**, which represents the cost of assigning the first to the second.
_weights_ is a matrix, but a **_weight_** is a map from an object to a target.
Here, I am only refering to the comcept _weight_.

2017-03-29 09:37 UTC, MarcoCouto commented on README.md
> +* **weight**: a map from **object** to **target**, which represents the cost of assigning the first to the second.
The input to the module is in a form of a matrix, but it could be something else in the future.
I think the _weight_ concept could be referred to as a map, and all _weights_ as a list of maps or something, don't you think? Or should the name **map** be switched to something else (like **association**)?

2017-03-29 09:53 UTC, fntneves commented on README.md
> +* **weight**: a map from **object** to **target**, which represents the cost of assigning the first to the second.
Following your intention to define what weight is, I would say that it is *the cost ....*

Regarding your second comment, I think if we change the input type, then we'll update docs accordingly. For now, it is a list. What do you think?

2017-03-29 10:06 UTC, MarcoCouto commented on README.md
> +* **weight**: a map from **object** to **target**, which represents the cost of assigning the first to the second.
Yes, _cost_ is a more understandable concept then _weight_. I will switch it.

Regarding the other issue, I think refering to _weights/costs_ as a list is not completely correct...
Lets try building a definition. First try:
- _weights/costs_ is a collection, which contains for each _target_ the _cost_ of assigning every _object_ to it, and is represented as a matrix.
What do you think?

2017-03-29 11:10 UTC, fntneves commented on README.md
> +* **weight**: a map from **object** to **target**, which represents the cost of assigning the first to the second.
I like it! It is now very clear.
IMO, I would change to your suggestion!

2017-03-29 11:27 UTC, MarcoCouto commented on README.md
> +* **weight**: a map from **object** to **target**, which represents the cost of assigning the first to the second.
Ok! Let me change the rest and I'll commit the changes

2017-03-29 16:42 UTC, fntneves requested changes
Please revert costs to weights, except its definition.
Update tasks in Usage section.
Add full code to Usage section.

2017-03-29 16:42 UTC, fntneves commented on README.md
> +* **cost**: a value associated between an **object** and a **target**, which represents the cost of assigning the first to the second.
Change to this:

weight: represents the cost of assigning a given object to a target.

2017-03-29 16:42 UTC, fntneves commented on README.md
>  }
**Tasks**: Front-end Development, Back-end Development, Testing, Documentation.

What is your opinion about adding the full example in the end of this section?

Something like:

Here is the full code:
```python
...
```

2017-03-29 18:21 UTC, MarcoCouto commented on README.md
>  }
I can agree on that. Maybe it turns out to be a little too repetitive, but we'll see.

2017-03-29 18:32 UTC, fntneves commented on README.md
>  }
I understand, but this is good for "copy-paster" people for a first execution :D

2017-03-29 22:21 UTC, fntneves commented
For me, its OK. I approve this.

2017-03-29 22:22 UTC, fntneves approved these changes

2017-03-30 08:29 UTC, Hugainz commented on README.md
> +The following three lists are given as input to the module: **objects**, **targets** and **weights**.
I'd remove this sentece. See comments on line 4.

2017-03-30 08:30 UTC, Hugainz commented on README.md
> +In a more pratical way, this module considers 3 key components:
To simplify, I'd change this to 
> Pratically, this module considers the following components, which must be inputted:

2017-03-30 08:32 UTC, Hugainz commented on README.md
> +**Fair Distributor** is a module which (fairly) distributes a list of arbitrary **objects** through a set of **targets**.
I believe we want to clearly state that our distribution is fair. No need for braces :)

2017-03-30 08:34 UTC, Hugainz commented on README.md
Where does the concept of costs come from? If **costs** is found to be a preferable nomenclature we should replace weights with costs altogether.

2017-03-30 08:36 UTC, fntneves commented on README.md
> +In a more pratical way, this module considers 3 key components:
Does 'inputted' mean this ? 🤔 

At least it is not very common in README.
Maybe "must be given as input".

2017-03-30 08:39 UTC, MarcoCouto commented on README.md
> +In a more pratical way, this module considers 3 key components:
I think "inputted" os not correct. At least, I never saw it before.

2017-03-30 08:46 UTC, MarcoCouto commented on README.md
> +**Fair Distributor** is a module which (fairly) distributes a list of arbitrary **objects** through a set of **targets**.
I agree. Yet, this is the first time the term appears, and we haven't define it yet. The ideia behind the braces is "ok, this is a fair distributor, but you don't know what fair os yet!" Obviously, I can remove the braces tho, if you disagree.

2017-03-30 08:47 UTC, MarcoCouto commented on README.md
Yes, I missed it. It should be weights

2017-03-30 08:48 UTC, Hugainz commented on README.md
> +In a more pratical way, this module considers 3 key components:
My mistake :)
Input is the word we are looking for.

2017-03-30 09:10 UTC, Hugainz commented on README.md
>  ## Contributions and Bugs
What do you think about this section? I believe it could be improved. 
My suggestion is to separate the text into more paragraphs and maybe rephrase/restructure them.

2017-03-30 09:15 UTC, Hugainz commented on README.md
> +**Fair Distributor** is a module which (fairly) distributes a list of arbitrary **objects** through a set of **targets**.
I get your point, but I'm not sure the braces add anything to the message. What do you think of making the word **fairly** a link to the section where we explain the concept?

2017-03-30 09:15 UTC, fntneves commented on README.md
>  ## Contributions and Bugs
It will need more work than what actually exists.

I'll take care of it in the future, since we must explain how to test things.

2017-03-30 09:15 UTC, MarcoCouto commented on README.md
>  ## Contributions and Bugs
Honestly, I think it is very clear :)
Can you be more specific in what you would change?

2017-03-30 09:17 UTC, MarcoCouto commented on README.md
> +**Fair Distributor** is a module which (fairly) distributes a list of arbitrary **objects** through a set of **targets**.
That is a great idea :) I'll do it ASAP.

2017-03-30 09:29 UTC, Hugainz commented on README.md
>  ## Contributions and Bugs
Ok @fntneves.
@MarcoCouto I suggest adding the missing paragraph between line 63 and 64 and leaving it then.
I'll sum up and request all changes.

2017-03-30 09:34 UTC, hgg requested changes
As discussed, it would be great to have the following changes:
* Remove braces from the word **fairly** in line 2 and make it a link to  **Our Meaning of Fairness** section.
* Change line 4 to "Pratically, this module considers the following components, which must be input:"
* Remove line 9.
* Change costs to weights in lines 13 and 14.
* Add an empty line (paragraph) between line 110 and 111.

2017-03-30 10:43 UTC, andrebrandao21 commented on README.md
> +need to assign **4** tasks through a set of **3** teams: _A_, _B_ and _C_.
You should change the ".need" to "And you need to".

2017-03-30 10:47 UTC, andrebrandao21 commented on README.md
> +It is necessary to create a data strcuture for each component. **Objects** and **targets** are lists, while **weights** is a collection, which contains for each target the cost of assigning every obj
Change "is" to "are", it's plural!

2017-03-30 10:54 UTC, fntneves commented on README.md
> +It is necessary to create a data strcuture for each component. **Objects** and **targets** are lists, while **weights** is a collection, which contains for each target the cost of assigning every obj
"strcuture"

2017-03-30 16:02 UTC, MarcoCouto commented on README.md
> +In a more pratical way, this module considers 3 key components:
I still don't like the _Pratically_ at the beginning of the sentence.
What do you think about this: 
```To be more explicit, this module considers 3 key components:
* object* : ...
* target* : ...
* weight* : ...
A list of each of this components must be given as input to ...
```
?

2017-03-30 16:18 UTC, MarcoCouto commented on README.md
> +need to assign **4** tasks through a set of **3** teams: _A_, _B_ and _C_.
Something happened there... The sentence shouldn't start like that. I'll propose something a bit different ;)

2017-03-30 16:23 UTC, MarcoCouto commented on README.md
> +In a more pratical way, this module considers 3 key components:
Well... Maybe `A collection of each...`, since `weights` is a matrix, thus is also a collection.

2017-03-30 16:32 UTC, hgg requested changes
We're almost there :+1: 
I'd just like to ask you to fix two typos:
* Line 9 : **this** should be **these**
* Line 12: **distribute** 

Also, as a suggestion only:
On Line 4, change **To be more explicit** to **Simply put**

2017-03-30 16:45 UTC, fntneves commented on README.md
> +In a more pratical way, this module considers 3 key components:
What about *This module considers...* ?

2017-03-30 21:19 UTC, hgg requested changes
I'm really sorry I missed this last time. 
Line 9: _...these components **are** given as..._
I believe this will be the last change :)

2017-03-30 21:27 UTC, fntneves commented
@Hugainz I am pretty sure that it is correct. It is related to the collection, not to its components. Please confirm.

2017-03-30 21:35 UTC, MarcoCouto commented
Exactly :)

2017-03-30 21:37 UTC, fntneves requested changes
Fix link to the section about the meaning of fairness.

2017-03-30 21:37 UTC, fntneves commented on README.md
> +**Fair Distributor** is a module which [fairly](our-meaning-of-fairness) distributes a list of arbitrary **objects** through a set of **targets**.
This link is not working. Fix it by adding a # at the beginning of the target section.

`[fairly](#our-meaning-of-fairness)`

2017-03-31 08:55 UTC, fntneves approved these changes

2017-03-31 09:12 UTC, hgg approved these changes
You're right. I'm accepting this :+1:

2017-03-31 19:28 UTC, merged