Fixing README.md.
Hackathonners/vania pull request #8
Opened 2017-06-18 22:23 UTC by mrjbq7

The example output was wrong, and also order it A, B, C.

2017-06-19 19:33 UTC, fntneves requested changes
A little change and it will be merged :+1:

2017-06-19 19:33 UTC, fntneves commented on README.md
> +    'Team C': ['Testing', 'Documentation'],     # Team C does the Testing and Documentation
Please, remove the trailing comma here, and it is ready to merge.

2017-06-19 23:06 UTC, mrjbq7 commented
Oh right, thanks.  I force pushed new change so maybe this is okay for you?

2017-06-20 08:19 UTC, fntneves approved these changes

2017-06-20 08:20 UTC, merged

2017-06-20 08:21 UTC, fntneves commented
Thank you for you contribution 👍